apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-deployment
  labels:
    app: weather-station
spec:
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
      - name: weather-station
        image: weather-station:latest       
        imagePullPolicy: Never